services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: homeiot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: .
    restart: unless-stopped
    ports: 
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS="-Dspring.datasource.url=jdbc:postgresql://db:5432/homeiot"
    depends_on:
      - db

volumes:
  pgdata: